---
application:
  name: "saturn-discord-bot"
  project: "saturn-discord-bot"
  organization: "QoveryCommunity"
  storage:
  - name: "bot"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/bot"
databases:
- type: "MONGODB"
  name: "botdb"
  version: "4.4"
routers:
- name: "main-saturn-discord-bot"
  routes:
  - application_name: "saturn-discord-bot"
    paths:
    - "/*"
